FROM openjdk:8-alpine
MAINTAINER Your Name <you@example.com>

ADD target/knowledge_graph_navigator-ui_clj-0.0.1-SNAPSHOT-standalone.jar /knowledge_graph_navigator-ui_clj/app.jar

EXPOSE 8080

CMD ["java", "-jar", "/knowledge_graph_navigator-ui_clj/app.jar"]
